# Generated by Django 4.2 on 2023-12-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_acerca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Elier Jerez', max_length=100)),
                ('content', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='core')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='acerca',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='core'),
        ),
    ]
