# Generated by Django 4.2 on 2023-12-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='country',
            field=models.IntegerField(default=1),
        ),
    ]
